///*
// * This source file was generated by the Gradle 'init' task
// */
//package main;
//
//import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;
//
//class MainTest {
//
//	@Test
//	void testMainRunsWithoutExceptions() {
//		assertDoesNotThrow(() -> Main.main(new String[] {}), "Main method should run without throwing exceptions");
//	}
//}
